CREATE TABLE `Clientes`(
	`Civil` VARCHAR(40),
	`ControleCaixaFlag` VARCHAR(40),
	`CPF` VARCHAR(40),
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`EvangelicoAceiteJesusAsilar` VARCHAR(40),
	`EvangelicoDenominacao` VARCHAR(40),
	`EvangelicoDetalhes` VARCHAR(40),
	`EvangelicoFlag` VARCHAR(40),
	`EvangelicoMinisterio` VARCHAR(40),
	`EvangelicoPastor` VARCHAR(40),
	`EvangelicoSetor` VARCHAR(40),
	`EvangelicoTipo` VARCHAR(40),
	`Id` BIGINT NOT NULL AUTO_INCREMENT,
	`InativoData` DATETIME(3),
	`InativoDetalhes` VARCHAR(40),
	`InativoMotivo` VARCHAR(40),
	`Interditado` VARCHAR(40),
	`InterditadoCurador` VARCHAR(40),
	`InterditadoCuradorEmail` VARCHAR(40),
	`InterditadoCuradorTelefone` VARCHAR(40),
	`InterditadoData` DATETIME(3),
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`Mae` VARCHAR(40),
	`MotivoAbrigamento` VARCHAR(40),
	`MotivoEscolha` VARCHAR(40),
	`Nacionalidade` VARCHAR(40),
	`Naturalidade` VARCHAR(40),
	`ObitoDocumento` VARCHAR(40),
	`Pai` VARCHAR(40),
	`RG` VARCHAR(40),
	`SoftDeleteFlag` BOOLEAN,
	`SUS` VARCHAR(40),
	`TituloEleitor` VARCHAR(40),
	PRIMARY KEY(`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE `Clientes`
	ADD CONSTRAINT `bfce2c33816f113cf324217201c390` UNIQUE KEY(`Id`);
